[server]
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 2000
# Mantiene viva la conexion WebSocket
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = false
